version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - npm install --save truffle-hdwallet-provider@web3-one
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npm install --save truffle-hdwallet-provider@web3-one
      - npx truffle test
      - truffle migrate --network besuWallet
stages:
  - pipeline:
      jobs:
        - compile
        - test